# Generated by Django 4.0.5 on 2022-06-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakonizone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
