# Generated by Django 4.0.5 on 2022-06-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakonizone', '0002_alter_business_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
