# Generated by Django 4.0.5 on 2022-06-21 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wakonizone', '0003_profile_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='post',
            name='neighbourhood',
        ),
    ]
